name: BranchName

on:
  push:
    branches:
      - main

jobs: 
  BranchJob: 
    runs-on: ubuntu-latest
    steps:
      - name: Print Branch Nameeeee
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT