name: BranchName

on:
  push:
    branches:
      - main

jobs: 
  BranchJob: 
  name: Branch Job 
  id: branchname
  run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
